### ISSUE TITLE
Integer parameter shows up as string-type in help

### ISSUE THREAD

**Issue by ClaesBas** [stevenroose/gonfig#11]
Try this:
```
var config = struct {
	Bits int `id:"bits" short:"b" desc:"Number of bits for the certificate"`
	ConfigFile string `short:"c"`
}{
	Bits: 4096,
}
```

Output for -h:
```
programname -h
Usage of .../programname:
  -b, --bits string         Number of bits for the certificate
  -c, --configfile string
  -h, --help                print this help menu
```

**Comment by stevenroose** [comment]
Yeah I saw that. I though the values would show up unquoted and without a
type mention, but apparently pflag does that.

It won't be pretty, but I'll have to add a big switch in the method
creating the flags. We read the values as strings anyways because we have
cast functionality for environment variables.

I'll fix this when I get the chance next week! Thanks for the feedback!

**Comment by stevenroose** [comment]
@ClaesBas Can you take a look at #12 and see if that is sufficient? Thanks!
