### ISSUE TITLE
Problem with numeric variables

### ISSUE THREAD

**Issue by s4kas** [stevenroose/gonfig#18]
Hi Steven,

Having a problem with a numeric variable:

- If i put 0018 in the config file and use a int type i get only 18;
- If i put 0018 in the config file and use a string type i get an error:
`error loading config vars from config file: incompatible type: float64 not convertible to string`

Can u check it?

**Comment by stevenroose** [comment]
Hmm, that makes sense. What file format are you using? While YAML doesn't need quotes around strings, both JSON and TOML do. Check examples below:
```json
# JSON
{
  "myVar": 042
}
```
```toml
# TOML
myVar = 042
```

In these two examples, you're creating a JSON/TOML integer field. The interpreter will interpret that as an integer. If you want a string, it needs to look like this:
```json
# JSON
{
  "myVar": "042"
}
```
```toml
# TOML
myVar = "042"
```

So for JSON and TOML, the behavior of gonfig is not wrong.

However, for YAML, it could be a problem. Since for YAML, the quotes are optional, so this is a valid way to define a string variable (even though it's not good practice):
```yaml
# YAML
myVar: 042
```

Let me look into automatically trying to convert to string in the case of a type mismatch.

**Comment by stevenroose** [comment]
@s4kas 

This diff would likely fix it (apply with `git apply <diffile>`):
```diff
diff --git a/values.go b/values.go
index 9090788..e691f23 100644
--- a/values.go
+++ b/values.go
@@ -51,6 +51,12 @@ func (o *option) setValue(v reflect.Value) error {
 		return convertSlice(v, o.value)
 	}
 
+	// If target type is string, convert to string.
+	if o.value.Type().Kind() == reflect.String {
+		o.value.SetString(fmt.Sprintf("%v", v.Interface()))
+		return nil
+	}
+
 	return convertibleError(v, o.value.Type())
 }
 ```

However, I'm not sure if that's good. This can cause weird stuff. In the case a config variable is string and it get's parsed as a slice or map, f.e., it will put strangely formatted (`fmt` slide/map) stuff in the variable... Not sure what to do.

**Comment by stevenroose** [comment]
Gonna close this. Was a file syntax problem, not a gonfig problem.
